### ISSUE TITLE
Update ownCloud to the latest version

### ISSUE THREAD

**Issue by ichristo** [ichristo/owncloud-openshift-quickstart#2]
Need to update this quickstart to use the latest version of ownCloud.

**Comment by williamtheaker** [comment]
Could I clone this repo and replace /php with Owncloud 5.0?

**Comment by ichristo** [comment]
Yes.  I updated the repo with 5.0.  I removed everything in php to avoid leaving any obsolete files.  Make sure to include the .htaccess file as well.
